name: check-storoj



on: 
  push: 
    branches:
      - main

jobs:
  test-watchdog:
    runs-on: ubuntu-latest
    steps:
      - name: Get my code   # <-- ВОТ ЭТОТ ШАГ ПЕРВЫЙ
        uses: actions/checkout@v4

      - name: Debug - Find server.log
        run: |
          echo "=== Где я нахожусь? ==="
          pwd
          ls -la
          find . -name "server.log"
          # … и остальные твои шаги

  
      
